 INSERT INTO roles VALUES (1, 'USER'), (2, 'ADMINISTRATOR');
--
-- INSERT INTO users VALUES(1, 'petincka@abv.bg', '123', 'petincka');

INSERT INTO recipes (image, ingredients, instructions, likes, name, time_for_cooking, added_by_id, category_id) VALUES
("/images/watermelon-salad.webp", '4 cups arugula, 3 cups watermelon, 1/4 cup mint leaves, 1/4 cup feta cheese, 2 cups chicken, balsamic vinegar, balsamic vinegar', 'Chop the watermelon into cubes, and shred the chicken, as needed. Finely slice the mint, and crumble the feta. Spread the arugula over a serving platter. Top the arugula with chicken, watermelon, feta and mint. Drizzle the salad with balsamic vinegar, and olive oil.', '0', 'Watermelon, Feta, and Mint Salad', '10', '1', '1'),
("/images/macaroni-salad.webp", '3/4 tsp. salt, 8 oz. elbow macaroni, 1/2 cup mayonnaise, 1/4 cup sour cream, 1 tsp. lemon zest, 1 Tbsp. lemon juice, 1 stalk celery, 2 green onions, 1/4 cup fresh flat-leaf parsley, 1/4 cup sweet relish, 4 oz. diced pimentos, 1/2 tsp. black pepper', 'Bring a medium pot of salted water to a boil over high heat. Cook macaroni according to package directions until barely tender (al dente), about 9 minutes. Drain macaroni, then rinse with cold water to stop the cooking, and drain. Let macaroni stand in the colander about 10 minutes to dry. Meanwhile, in a large bowl, stir together mayonnaise, sour cream, lemon zest, and lemon juice. Finely chop celery, and chop green onions. Add celery and green onions to bowl with mayonnaise mixture along with parsley, sweet relish, about three-quarters of the pimentos, 3/4 tsp. salt, and the pepper, and stir to blend. Chill if macaroni isn’t ready yet. Add cooked macaroni, stirring to combine. Taste and add more salt and pepper if you like. Sprinkle salad with a little more parsley and with the reserved pimentos and serve, or chill it, covered, up to 3 days. (Salad will absorb some of the dressing as it stands.)', '0', 'Macaroni Salad', '25', '1', '1'),
("/images/spinach-salad.webp", '1/2 cup pecans, 3 Tbsp. extra virgin olive oil, 1 1/2 Tbsp. apple cider vinegar, 1 Tbsp. honey, 1 tsp. Dijon mustard, 1/4 tsp. salt, 1/4 tsp. black pepper, 4 oz. baby spinach leaves, 1/2 cup dried cranberries, salt, black pepper', 'Preheat the oven to 350°F. Spread the nuts evenly in a pie pan. Toast the nuts on middle rack of oven until fragrant and a shade darker, 8-10 minutes. Check to see that nuts are done. Remove from oven or add time as needed. Let nuts cool for about 5 minutes. Combine the oil, vinegar, honey, mustard, salt, and pepper in a small bowl. Combine the spinach, cranberries, pecans, and as much dressing as desired in a large bowl. Add more salt and pepper to taste and serve.', '0', 'Spinach Salad with Toasted Pecans', '20', '1', '1'),
("/images/cucumber-salad.webp", '2 English cucumbers, 3 Tbsp. rice vinegar, 1 Tbsp. fish sauce, 2 Tbsp. sugar, 1/4 tsp. chili flakes, 1 Tbsp. sesame seeds, 1 tsp. salt, 1/2 tsp. pepper, 2 Tbsp. soy sauce', 'Combine all of the ingredients in a large mixing bowl. Toss well to combine, then cover with plastic wrap and refrigerate. Serve with Thai-Style Oven Baked Ribs.', '0', 'Sweet and Sour Smashed Cucumber Salad', '10', '1', '1'),
("/images/ginger-salad.webp", '1 lb. boneless pork loin, 1/2 cup orange juice, 2 Tbsp. ginger, 2 cups melon balls, 1 papaya, 2 Tbsp. orange liqueur, 6 cups mixed greens, 1/2 cup peach yogurt', 'In medium saucepan combine orange juice and ginger; bring to a simmer and add pork cubes. Simmer for about 5 minutes, until pork is cooked. Remove pork and remaining liquid to bowl, refrigerate uncovered to cool slightly, about 5-10 minutes. In medium bowl gently toss together melon, papaya, Grand Marnier, pork cubes and cooking liquid. On each of four plates place 1 1/2 cups salad greens. Serve equal portions pork-melon mixture atop greens, topped with 2 tablespoons yogurt.', '0', 'Gingered Pork and Melon Salad', '20', '1', '1');



